/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SocRouteImport } from './routes/_soc'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SocAnalyzerRouteImport } from './routes/_soc.analyzer'
import { Route as SocDashboardRouteImport } from './routes/_soc.dashboard'
import { Route as SocMitreRouteImport } from './routes/_soc.mitre'
import { Route as SocSettingsRouteImport } from './routes/_soc.settings'
import { Route as SocIncidentsIndexRouteImport } from './routes/_soc.incidents.index'
import { Route as SocIncidentsIdRouteImport } from './routes/_soc.incidents.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SocRoute = SocRouteImport.update({
  id: '/_soc',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SocAnalyzerRoute = SocAnalyzerRouteImport.update({
  id: '/analyzer',
  path: '/analyzer',
  getParentRoute: () => SocRoute,
} as any)
const SocDashboardRoute = SocDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SocRoute,
} as any)
const SocMitreRoute = SocMitreRouteImport.update({
  id: '/mitre',
  path: '/mitre',
  getParentRoute: () => SocRoute,
} as any)
const SocSettingsRoute = SocSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SocRoute,
} as any)
const SocIncidentsIndexRoute = SocIncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => SocRoute,
} as any)
const SocIncidentsIdRoute = SocIncidentsIdRouteImport.update({
  id: '/incidents/$id',
  path: '/incidents/$id',
  getParentRoute: () => SocRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analyzer': typeof SocAnalyzerRoute
  '/dashboard': typeof SocDashboardRoute
  '/mitre': typeof SocMitreRoute
  '/settings': typeof SocSettingsRoute
  '/incidents/$id': typeof SocIncidentsIdRoute
  '/incidents/': typeof SocIncidentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analyzer': typeof SocAnalyzerRoute
  '/dashboard': typeof SocDashboardRoute
  '/mitre': typeof SocMitreRoute
  '/settings': typeof SocSettingsRoute
  '/incidents/$id': typeof SocIncidentsIdRoute
  '/incidents': typeof SocIncidentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_soc': typeof SocRouteWithChildren
  '/login': typeof LoginRoute
  '/_soc/analyzer': typeof SocAnalyzerRoute
  '/_soc/dashboard': typeof SocDashboardRoute
  '/_soc/mitre': typeof SocMitreRoute
  '/_soc/settings': typeof SocSettingsRoute
  '/_soc/incidents/$id': typeof SocIncidentsIdRoute
  '/_soc/incidents/': typeof SocIncidentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analyzer'
    | '/dashboard'
    | '/mitre'
    | '/settings'
    | '/incidents/$id'
    | '/incidents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analyzer'
    | '/dashboard'
    | '/mitre'
    | '/settings'
    | '/incidents/$id'
    | '/incidents'
  id:
    | '__root__'
    | '/'
    | '/_soc'
    | '/login'
    | '/_soc/analyzer'
    | '/_soc/dashboard'
    | '/_soc/mitre'
    | '/_soc/settings'
    | '/_soc/incidents/$id'
    | '/_soc/incidents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SocRoute: typeof SocRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_soc': {
      id: '/_soc'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_soc/analyzer': {
      id: '/_soc/analyzer'
      path: '/analyzer'
      fullPath: '/analyzer'
      preLoaderRoute: typeof SocAnalyzerRouteImport
      parentRoute: typeof SocRoute
    }
    '/_soc/dashboard': {
      id: '/_soc/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof SocDashboardRouteImport
      parentRoute: typeof SocRoute
    }
    '/_soc/mitre': {
      id: '/_soc/mitre'
      path: '/mitre'
      fullPath: '/mitre'
      preLoaderRoute: typeof SocMitreRouteImport
      parentRoute: typeof SocRoute
    }
    '/_soc/settings': {
      id: '/_soc/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SocSettingsRouteImport
      parentRoute: typeof SocRoute
    }
    '/_soc/incidents/': {
      id: '/_soc/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof SocIncidentsIndexRouteImport
      parentRoute: typeof SocRoute
    }
    '/_soc/incidents/$id': {
      id: '/_soc/incidents/$id'
      path: '/incidents/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof SocIncidentsIdRouteImport
      parentRoute: typeof SocRoute
    }
  }
}

interface SocRouteChildren {
  SocAnalyzerRoute: typeof SocAnalyzerRoute
  SocDashboardRoute: typeof SocDashboardRoute
  SocMitreRoute: typeof SocMitreRoute
  SocSettingsRoute: typeof SocSettingsRoute
  SocIncidentsIdRoute: typeof SocIncidentsIdRoute
  SocIncidentsIndexRoute: typeof SocIncidentsIndexRoute
}

const SocRouteChildren: SocRouteChildren = {
  SocAnalyzerRoute: SocAnalyzerRoute,
  SocDashboardRoute: SocDashboardRoute,
  SocMitreRoute: SocMitreRoute,
  SocSettingsRoute: SocSettingsRoute,
  SocIncidentsIdRoute: SocIncidentsIdRoute,
  SocIncidentsIndexRoute: SocIncidentsIndexRoute,
}

const SocRouteWithChildren = SocRoute._addFileChildren(SocRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SocRoute: SocRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
